name: Build and test skaled
on:
  push:
    branches-ignore:
      - 'master'
      - 'beta'
      - 'stable'

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        NO_ULIMIT_CHECK: 1
        NO_NTP_CHECK: 1
        ccache_compress: 'true'
        ccache_compresslevel: 9
        TARGET: all
        CMAKE_BUILD_TYPE: Debug

    steps:
      - name: Extract repo name
        run: echo ::set-env name=REPOSITORY_NAME::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}')
        shell: bash
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      - name: checkout
        uses: actions/checkout@v2
      - name: Install packages
        run: |
          sudo apt install autoconf build-essential cmake libprocps-dev libtool texinfo wget yasm flex bison btrfs-progs python3 python3-pip gawk git vim doxygen
          sudo apt install make build-essential cmake pkg-config libgnutls28-dev libssl-dev unzip zlib1g-dev libgcrypt20-dev docker.io gcc-11 g++-11 gperf clang-format-11 gnutls-dev
          sudo apt install nettle-dev libhiredis-dev redis-server google-perftools libgoogle-perftools-dev lcov
          sudo apt-get install libv8-dev
          sudo apt-get purge -y libbz2-dev && apt-get autoremove -y
      - name: Set gcc
        run: |
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 11
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 11
          sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-11 11
          sudo update-alternatives --install /usr/bin/gcov-dump gcov-dump /usr/bin/gcov-dump-11 11
          sudo update-alternatives --install /usr/bin/gcov-tool gcov-tool /usr/bin/gcov-tool-11 11
          gcc --version
      - name: Build dependencies
        run: |
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          cd deps
          #######################################./clean.sh
          # prepare boost library
          curl -L https://archives.boost.io/release/1.87.0/source/boost_1_87_0.tar.bz2 -o ../libconsensus/libBLS/deps/boost_1_87_0.tar.bz2          
          rm -f ./libwebsockets-from-git.tar.gz
          ./build.sh DEBUG=1 PARALLEL_COUNT=$(nproc)
          cd ..

      - name: Build (default)
        uses: ./.github/actions/cmake-build
        with:
          build_dir: build
          cmake_build_type: ${{ env.CMAKE_BUILD_TYPE }}
          coverage: ${{ env.CODE_COVERAGE }}
          cmake_args: ""
          make_target: testeth

      - name: Testeth (full) verbosity 1
        uses: ./.github/actions/testeth-run
        with:
          build_dir: build
          mode: full
          verbosity: "1"

      - name: Testeth (full) verbosity 4
        uses: ./.github/actions/testeth-run
        with:
          build_dir: build
          mode: full
          verbosity: "4"

      - name: Print ccache stats after full build
        run: |
          ccache --show-stats

      - name: Build (historic)
        uses: ./.github/actions/cmake-build
        with:
          build_dir: build_historic
          cmake_build_type: ${{ env.CMAKE_BUILD_TYPE }}
          coverage: ${{ env.CODE_COVERAGE }}
          cmake_args: "-DHISTORIC_STATE=1"
          make_target: testeth

      - name: Testeth historic (JsonRpcSuite) verbosity 1
        uses: ./.github/actions/testeth-run
        with:
          build_dir: build_historic
          mode: historic
          verbosity: "1"

      - name: Testeth historic (JsonRpcSuite) verbosity 4
        uses: ./.github/actions/testeth-run
        with:
          build_dir: build_historic
          mode: historic
          verbosity: "4"

      - name: Build (FAIR)
        uses: ./.github/actions/cmake-build
        with:
          build_dir: build_fair
          cmake_build_type: ${{ env.CMAKE_BUILD_TYPE }}
          coverage: ${{ env.CODE_COVERAGE }}
          cmake_args: "-DFAIR=1"
          make_target: testeth

      - name: Testeth FAIR (full) verbosity 1
        uses: ./.github/actions/testeth-run
        with:
          build_dir: build_fair
          mode: full
          verbosity: "1"

      - name: Testeth FAIR (full) verbosity 4
        uses: ./.github/actions/testeth-run
        with:
          build_dir: build_fair
          mode: full
          verbosity: "4"

      - name: Build (FAIR-historic)
        uses: ./.github/actions/cmake-build
        with:
          build_dir: build_fair_historic
          cmake_build_type: ${{ env.CMAKE_BUILD_TYPE }}
          coverage: ${{ env.CODE_COVERAGE }}
          cmake_args: "-DFAIR=1 -DHISTORIC_STATE=1"
          make_target: testeth

      - name: Testeth FAIR-historic (JsonRpcSuite) verbosity 1
        uses: ./.github/actions/testeth-run
        with:
          build_dir: build_fair_historic
          mode: historic
          verbosity: "1"

      - name: Testeth FAIR-historic (JsonRpcSuite) verbosity 4
        uses: ./.github/actions/testeth-run
        with:
          build_dir: build_fair_historic
          mode: historic
          verbosity: "4"

      - name: Build (BITE2)
        uses: ./.github/actions/cmake-build
        with:
          build_dir: build_bite2
          cmake_build_type: ${{ env.CMAKE_BUILD_TYPE }}
          coverage: ${{ env.CODE_COVERAGE }}
          cmake_args: "-DBITE2=1"
          make_target: testeth

      - name: Testeth BITE2 (full) verbosity 1
        uses: ./.github/actions/testeth-run
        with:
          build_dir: build_bite2
          mode: full
          verbosity: "1"

      - name: Testeth BITE2 (full) verbosity 4
        uses: ./.github/actions/testeth-run
        with:
          build_dir: build_bite2
          mode: full
          verbosity: "4"

      - name: Build (BITE2-historic)
        uses: ./.github/actions/cmake-build
        with:
          build_dir: build_bite2_historic
          cmake_build_type: ${{ env.CMAKE_BUILD_TYPE }}
          coverage: ${{ env.CODE_COVERAGE }}
          cmake_args: "-DBITE2=1 -DHISTORIC_STATE=1"
          make_target: testeth

      - name: Testeth BITE2-historic (JsonRpcSuite) verbosity 1
        uses: ./.github/actions/testeth-run
        with:
          build_dir: build_bite2_historic
          mode: historic
          verbosity: "1"

      - name: Testeth BITE2-historic (JsonRpcSuite) verbosity 4
        uses: ./.github/actions/testeth-run
        with:
          build_dir: build_bite2_historic
          mode: historic
          verbosity: "4"
